### ISSUE TITLE
Many issues while generating app bundle

### ISSUE THREAD

**Issue by mangeshdotco** [DevelopGadget/flutter_startapp#1]
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'void setContentView(android.view.View)' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'android.view.Window getWindow()' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'void addContentView(android.view.View,android.view.ViewGroup$LayoutParams)' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'android.content.res.Resources$Theme getTheme()' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'android.content.res.Resources getResources()' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'androidx.fragment.app.FragmentManager getSupportFragmentManager()' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'android.content.Intent getIntent()' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'android.content.Context getApplicationContext()' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'android.content.pm.PackageManager getPackageManager()' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'android.content.ComponentName getComponentName()' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterActivity: can't find referenced method 'android.content.pm.ApplicationInfo getApplicationInfo()' in program class io.flutter.embedding.android.FlutterActivity
Warning: io.flutter.embedding.android.FlutterFragment: can't find referenced method 'void setArguments(android.os.Bundle)' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment: can't find referenced method 'androidx.fragment.app.FragmentActivity getActivity()' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment: can't find referenced method 'androidx.lifecycle.Lifecycle getLifecycle()' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment: can't find referenced method 'android.os.Bundle getArguments()' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment: can't find referenced method 'android.content.Context getContext()' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment: can't find referenced method 'android.content.res.Resources getResources()' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment$1: can't find referenced method 'androidx.fragment.app.FragmentActivity getActivity()' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.android.FlutterFragment$Builder: can't find referenced method 'void setArguments(android.os.Bundle)' in program class io.flutter.embedding.android.FlutterFragment
Warning: io.flutter.embedding.engine.FlutterEngineAndroidLifecycle: can't find referenced method 'void markState(androidx.lifecycle.Lifecycle$State)' in program class io.flutter.embedding.engine.FlutterEngineAndroidLifecycle
Note: a.a.b.b: can't find dynamically referenced class truenet.kotlin.internal.jdk8.JDK8PlatformImplementations
Note: a.a.b.b: can't find dynamically referenced class truenet.kotlin.internal.JRE8PlatformImplementations
Note: a.a.b.b: can't find dynamically referenced class truenet.kotlin.internal.JRE7PlatformImplementations
Note: a.a.d.b.m: can't find dynamically referenced class truenet.kotlin.reflect.jvm.internal.ReflectionFactoryImpl
Note: com.startapp.common.a.b: can't find dynamically referenced class com.google.android.gms.ads.identifier.AdvertisingIdClient
Note: io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors: can't find dynamically referenced class android.util.LongArray
Note: com.startapp.android.publish.adsCommon.m accesses a field 'WRAPPER_VERSION' dynamically
Note: com.startapp.common.c.a accesses a field 'TYPE' dynamically       
      Maybe this is library field 'android.os.Build { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.CallLog$Calls { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.Contacts$ContactMethodsColumns { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.Contacts$OrganizationColumns { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.Contacts$PhonesColumns { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.ContactsContract$AggregationExceptions { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.ContactsContract$CommonDataKinds$CommonColumns { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.ContactsContract$PhoneLookupColumns { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.Telephony$Carriers { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.Telephony$Mms$Addr { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.Telephony$TextBasedSmsColumns { java.lang.String TYPE; }'
      Maybe this is library field 'android.provider.Telephony$ThreadsColumns { java.lang.String TYPE; }'
      Maybe this is library field 'java.lang.Boolean { java.lang.Class TYPE; }'
      Maybe this is library field 'java.lang.Byte { java.lang.Class TYPE; }'
      Maybe this is library field 'java.lang.Character { java.lang.Class TYPE; }'
      Maybe this is library field 'java.lang.Double { java.lang.Class TYPE; }'
      Maybe this is library field 'java.lang.Float { java.lang.Class TYPE; }'
      Maybe this is library field 'java.lang.Integer { java.lang.Class TYPE; }'
      Maybe this is library field 'java.lang.Long { java.lang.Class TYPE; }'
      Maybe this is library field 'java.lang.Short { java.lang.Class TYPE; }'
      Maybe this is library field 'java.lang.Void { java.lang.Class TYPE; }'
      Maybe this is library field 'java.lang.annotation.ElementType { java.lang.annotation.ElementType TYPE; }'
Note: the configuration keeps the entry point 'com.startapp.a.a.a.a { java.lang.Class a(a.a.d.b.e); }', but not the descriptor class 'a.a.d.b.e'
Note: the configuration keeps the entry point 'com.startapp.android.publish.ads.banner.bannerstandard.c { c(com.b.a.a.a.b.d,com.b.a.a.a.b.d); }', but not the descriptor class 'com.b.a.a.a.b.d'
Note: the configuration keeps the entry point 'com.startapp.android.publish.ads.banner.bannerstandard.c { c(com.b.a.a.a.b.d,com.b.a.a.a.b.d); }', but not the descriptor class 'com.b.a.a.a.b.d'
Note: the configuration keeps the entry point 'com.startapp.android.publish.ads.banner.bannerstandard.c { com.startapp.android.publish.ads.banner.bannerstandard.c a(com.b.a.a.a.b.d,com.b.a.a.a.b.d); }', but not the descriptor class 'com.b.a.a.a.b.d'
Note: the configuration keeps the entry point 'com.startapp.android.publish.ads.banner.bannerstandard.c { com.startapp.android.publish.ads.banner.bannerstandard.c a(com.b.a.a.a.b.d,com.b.a.a.a.b.d); }', but not the descriptor class 'com.b.a.a.a.b.d'
Note: the configuration keeps the entry point 'com.startapp.android.publish.adsCommon.a.i { i(com.b.a.a.a.b.b); }', but not the descriptor class 'com.b.a.a.a.b.b'
Note: the configuration keeps the entry point 'com.startapp.android.publish.adsCommon.a.i { com.startapp.android.publish.adsCommon.a.i a(com.b.a.a.a.b.b); }', but not the descriptor class 'com.b.a.a.a.b.b'
Note: the configuration keeps the entry point 'com.startapp.android.publish.adsCommon.j.a { void a(com.b.a.a.a.b.b); }', but not the descriptor class 'com.b.a.a.a.b.b'
Note: the configuration keeps the entry point 'com.truenet.android.Link { Link(java.lang.String,java.lang.String,java.util.Map,java.lang.String,java.lang.String,java.lang.String,java.lang.String,long,boolean,com.truenet.android.b,java.lang.String,int,a.a.a.a); }', but not the descriptor class 'a.a.a.a'
Note: the configuration keeps the entry point 'com.truenet.android.LinksData { LinksData(long,int,boolean,int,long,java.util.List,int,a.a.a.a); }', but not the descriptor class 'a.a.a.a'
Note: the configuration keeps the entry point 'com.truenet.android.TrueNetSDK$a { void a(android.content.Context,java.lang.String,a.a.d.a.a); }', but not the descriptor class 'a.a.d.a.a'
Note: the configuration keeps the entry point 'com.truenet.android.TrueNetSDK$a { void a(android.content.Context,a.a.d.a.a); }', but not the descriptor class 'a.a.d.a.a'
Note: the configuration keeps the entry point 'com.truenet.android.TrueNetSDK$a$a { TrueNetSDK$a$a(com.truenet.android.LinksData,java.util.concurrent.ConcurrentLinkedQueue,android.content.Context,a.a.d.a.a); }', but not the descriptor class 'a.a.d.a.a'
Note: the configuration keeps the entry point 'com.truenet.android.TrueNetSDK$a$b { TrueNetSDK$a$b(a.a.d.b.l$a,com.truenet.android.LinksData,android.content.Context,java.util.concurrent.ConcurrentLinkedQueue); }', but not the descriptor class 'a.a.d.b.l$a'
Note: the configuration keeps the entry point 'com.truenet.android.TrueNetSDK$a$c { TrueNetSDK$a$c(android.content.Context,a.a.d.a.a); }', but not the descriptor class 'a.a.d.a.a'
Note: the configuration keeps the entry point 'com.truenet.android.TrueNetSDK$a$d$a { TrueNetSDK$a$d$a(com.truenet.android.TrueNetSDK$a$d,a.a.d.b.l$a); }', but not the descriptor class 'a.a.d.b.l$a'
Note: the configuration keeps the entry point 'com.truenet.android.a.c { c(a.a.d.b.l$a,java.io.BufferedReader); }', but not the descriptor class 'a.a.d.b.l$a'
Note: the configuration keeps the entry point 'com.truenet.android.c$f { c$f(com.truenet.android.c,java.lang.String,a.a.d.b.l$a); }', but not the descriptor class 'a.a.d.b.l$a'
Note: the configuration keeps the entry point 'com.truenet.android.e { void a(a.a.d.a.a); }', but not the descriptor class 'a.a.d.a.a'
Note: the configuration keeps the entry point 'com.truenet.android.e { void a(a.a.d.a.b); }', but not the descriptor class 'a.a.d.a.b'
Note: the configuration keeps the entry point 'com.truenet.android.e$c { e$c(com.truenet.android.c,int,com.truenet.android.e,a.a.d.a.b); }', but not the descriptor class 'a.a.d.a.b'
Note: the configuration keeps the entry point 'com.truenet.android.f { f(a.a.d.a.b); }', but not the descriptor class 'a.a.d.a.b'
Note: there were 22 unkept descriptor classes in kept class members.    
      You should consider explicitly keeping the mentioned classes      
      (using '-keep').                                                  
      (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
Note: there were 6 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.  
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 2 accesses to class members by means of introspection. 
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').                           
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Warning: there were 20 unresolved references to program class members.  
         Your input classes appear to be inconsistent.                  
         You may need to recompile the code.                            
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                         2.9s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task bundleRelease failed with exit code 1

**Comment by DevFx16** [comment]
Add in proguard 

`-keep class com.startapp.** {
      *;
}

-keep class com.truenet.** {
      *;
}

-keepattributes Exceptions, InnerClasses, Signature, Deprecated, SourceFile,
LineNumberTable, *Annotation*, EnclosingMethod
-dontwarn android.webkit.JavascriptInterface
-dontwarn com.startapp.**

-dontwarn org.jetbrains.annotations.**`
